### ISSUE TITLE
ujson version restriction incompatible with sanic_oauth

### ISSUE THREAD

**Issue by LewisGaul** [ensoft/entrance#12]
I've just tried to upgrade the version of EnTrance we're using and hit a dependency clash due to the new enforcement of `ujson>=3`:
https://github.com/ensoft/entrance/blob/611b077e6102a3482dc7597c76337c3591278e01/python/setup.py#L31

It seems this is only to avoid getting `ujson==2`. The problem is that `sanic_oauth` breaks with `ujson==3` - admittedly this is a problem with `sanic_oauth`, but the project appears to be unmaintained.

One way I think this could be handled better in EnTrance is by specifying `ujson !=2.0.0, !=2.0.1, !=2.0.2, !=2.0.3`. Unfortunately I can't see a better way to do this, I guess breakages are normally restricted to a single patch version (is it really the case it's the entire 2.x range that's broken, as implied by the comment above the linked line?).

For the record, the `sanic_oauth` error looks like:
```
ERROR: [sanic.error] Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File ".../venv/lib/python3.6/site-packages/sanic/app.py", line 1238, in _run_response_middleware
    _response = await _response
  File "run.py", line 735, in save_session
    await request.app.session_interface.save(request, response)
  File ".../venv/lib/python3.6/site-packages/sanic_session/base.py", line 145, in save
    val = ujson.dumps(dict(request[self.session_name]))
TypeError: <sanic_oauth.core.UserInfo object at 0x7fb58230c908> is not JSON serializable
```

**Comment by LewisGaul** [comment]
Actually, looks like you can do `ujson!=2.*` :)
